#verb database
verbs = [
  ["anfangen", "fing an", "hat angefangen"],
  ["antworten", "antwortete", "hat geantwortet"],
  ["arbeiten", "arbeitete", "hat gearbeitet"],
  ["aufräumen", "räumte auf", "hat aufgeräumt"],
  ["aufwachen", "wachte auf", "ist aufgewacht"],
  ["aussehen", "sah aus", "hat ausgesehen"],
  ["baden", "badete", "hat gebadet"],
  ["beginnen", "begann", "hat begonnen"],
  ["bekommen", "bekam", "hat bekommen"],
  ["bestellen", "bestellte", "hat bestellt"],
  ["besuchen", "besuchte", "hat besucht"],
  ["bewerben", "bewarb", "hat beworben"],
  ["bezahlen", "bezahlte", "hat bezahlt"],
  ["bitten", "bat", "hat gebeten"],
  ["bleiben", "blieb", "ist geblieben"],
  ["blicken", "blickte", "hat geblickt"],
  ["brauchen", "brauchte", "hat gebraucht"],
  ["bringen", "brachte", "hat gebracht"],
  ["bürsten", "bürstete", "hat gebürstet"],
  ["danken", "dankte", "hat gedankt"],
  ["dauern", "dauerte", "hat gedauert"],
  ["denken", "dachte", "hat gedacht"],
  ["diskutieren", "diskutierte", "hat diskutiert"],
  ["drücken", "drückte", "hat gedrückt"],
  ["duschen", "duschte", "hat geduscht"],
  ["empfehlen", "empfahl", "hat empfohlen"],
  ["entscheiden", "entschied", "hat entschieden"],
]
